name: Dracula
description: 'A dark theme for Atom, Alfred, Emacs, iTerm, Slack, Sequel Pro, Sublime Text, Textmate, Terminal.app, Vim, Visual Studio Code, Xcode, and Zsh'
author: Zeno Rocha
url: https://draculatheme.com